package agent

type SelfConfig struct {
	Config struct {
		Datacenter string `json:"Datacenter"`
		NodeName   string `json:"NodeName"`
		NodeID     string `json:"NodeID"`
		Revision   string `json:"Revision"`
		Server     bool   `json:"Server"`
		Version    string `json:"Version"`
	} `json:"Config"`
	DebugConfig struct {
		ACLDatacenter          string `json:"ACLDatacenter"`
		ACLDefaultPolicy       string `json:"ACLDefaultPolicy"`
		ACLDisabledTTL         string `json:"ACLDisabledTTL"`
		ACLDownPolicy          string `json:"ACLDownPolicy"`
		ACLEnableKeyListPolicy bool   `json:"ACLEnableKeyListPolicy"`
		ACLMasterToken         string `json:"ACLMasterToken"`
		ACLPolicyTTL           string `json:"ACLPolicyTTL"`
		ACLRoleTTL             string `json:"ACLRoleTTL"`
		ACLTokenReplication    bool   `json:"ACLTokenReplication"`
		ACLTokenTTL            string `json:"ACLTokenTTL"`
		ACLTokens              struct {
			ACLAgentMasterToken string `json:"ACLAgentMasterToken"`
			ACLAgentToken       string `json:"ACLAgentToken"`
			ACLDefaultToken     string `json:"ACLDefaultToken"`
			ACLReplicationToken string `json:"ACLReplicationToken"`
			DataDir             string `json:"DataDir"`
			EnablePersistence   bool   `json:"EnablePersistence"`
			EnterpriseConfig    struct {
			} `json:"EnterpriseConfig"`
		} `json:"ACLTokens"`
		ACLsEnabled               bool          `json:"ACLsEnabled"`
		AEInterval                string        `json:"AEInterval"`
		AdvertiseAddrLAN          string        `json:"AdvertiseAddrLAN"`
		AdvertiseAddrWAN          string        `json:"AdvertiseAddrWAN"`
		AdvertiseReconnectTimeout string        `json:"AdvertiseReconnectTimeout"`
		AllowWriteHTTPFrom        []interface{} `json:"AllowWriteHTTPFrom"`
		AutoConfig                struct {
			Authorizer struct {
				AllowReuse bool `json:"AllowReuse"`
				AuthMethod struct {
					ACLAuthMethodEnterpriseFields struct {
					} `json:"ACLAuthMethodEnterpriseFields"`
					Config struct {
						BoundAudiences       interface{} `json:"BoundAudiences"`
						BoundIssuer          string      `json:"BoundIssuer"`
						ClaimMappings        interface{} `json:"ClaimMappings"`
						ClockSkewLeeway      int         `json:"ClockSkewLeeway"`
						ExpirationLeeway     int         `json:"ExpirationLeeway"`
						JWKSCACert           string      `json:"JWKSCACert"`
						JWKSURL              string      `json:"JWKSURL"`
						JWTSupportedAlgs     interface{} `json:"JWTSupportedAlgs"`
						JWTValidationPubKeys interface{} `json:"JWTValidationPubKeys"`
						ListClaimMappings    interface{} `json:"ListClaimMappings"`
						NotBeforeLeeway      int         `json:"NotBeforeLeeway"`
						OIDCDiscoveryCACert  string      `json:"OIDCDiscoveryCACert"`
						OIDCDiscoveryURL     string      `json:"OIDCDiscoveryURL"`
					} `json:"Config"`
					Description    string `json:"Description"`
					DisplayName    string `json:"DisplayName"`
					EnterpriseMeta struct {
					} `json:"EnterpriseMeta"`
					MaxTokenTTL string `json:"MaxTokenTTL"`
					Name        string `json:"Name"`
					RaftIndex   struct {
						CreateIndex int `json:"CreateIndex"`
						ModifyIndex int `json:"ModifyIndex"`
					} `json:"RaftIndex"`
					TokenLocality string `json:"TokenLocality"`
					Type          string `json:"Type"`
				} `json:"AuthMethod"`
				ClaimAssertions []interface{} `json:"ClaimAssertions"`
				Enabled         bool          `json:"Enabled"`
			} `json:"Authorizer"`
			DNSSANs         []interface{} `json:"DNSSANs"`
			Enabled         bool          `json:"Enabled"`
			IPSANs          []interface{} `json:"IPSANs"`
			IntroToken      string        `json:"IntroToken"`
			IntroTokenFile  string        `json:"IntroTokenFile"`
			ServerAddresses []interface{} `json:"ServerAddresses"`
		} `json:"AutoConfig"`
		AutoEncryptAllowTLS              bool          `json:"AutoEncryptAllowTLS"`
		AutoEncryptDNSSAN                []interface{} `json:"AutoEncryptDNSSAN"`
		AutoEncryptIPSAN                 []interface{} `json:"AutoEncryptIPSAN"`
		AutoEncryptTLS                   bool          `json:"AutoEncryptTLS"`
		AutopilotCleanupDeadServers      bool          `json:"AutopilotCleanupDeadServers"`
		AutopilotDisableUpgradeMigration bool          `json:"AutopilotDisableUpgradeMigration"`
		AutopilotLastContactThreshold    string        `json:"AutopilotLastContactThreshold"`
		AutopilotMaxTrailingLogs         int           `json:"AutopilotMaxTrailingLogs"`
		AutopilotMinQuorum               int           `json:"AutopilotMinQuorum"`
		AutopilotRedundancyZoneTag       string        `json:"AutopilotRedundancyZoneTag"`
		AutopilotServerStabilizationTime string        `json:"AutopilotServerStabilizationTime"`
		AutopilotUpgradeVersionTag       string        `json:"AutopilotUpgradeVersionTag"`
		BindAddr                         string        `json:"BindAddr"`
		Bootstrap                        bool          `json:"Bootstrap"`
		BootstrapExpect                  int           `json:"BootstrapExpect"`
		CAFile                           string        `json:"CAFile"`
		CAPath                           string        `json:"CAPath"`
		Cache                            struct {
			EntryFetchMaxBurst int     `json:"EntryFetchMaxBurst"`
			EntryFetchRate     float64 `json:"EntryFetchRate"`
		} `json:"Cache"`
		CertFile                   string        `json:"CertFile"`
		CheckDeregisterIntervalMin string        `json:"CheckDeregisterIntervalMin"`
		CheckOutputMaxSize         int           `json:"CheckOutputMaxSize"`
		CheckReapInterval          string        `json:"CheckReapInterval"`
		CheckUpdateInterval        string        `json:"CheckUpdateInterval"`
		Checks                     []interface{} `json:"Checks"`
		ClientAddrs                []string      `json:"ClientAddrs"`
		ConfigEntryBootstrap       []interface{} `json:"ConfigEntryBootstrap"`
		ConnectCAConfig            struct {
		} `json:"ConnectCAConfig"`
		ConnectCAProvider                      string        `json:"ConnectCAProvider"`
		ConnectEnabled                         bool          `json:"ConnectEnabled"`
		ConnectMeshGatewayWANFederationEnabled bool          `json:"ConnectMeshGatewayWANFederationEnabled"`
		ConnectSidecarMaxPort                  int           `json:"ConnectSidecarMaxPort"`
		ConnectSidecarMinPort                  int           `json:"ConnectSidecarMinPort"`
		ConnectTestCALeafRootChangeSpread      string        `json:"ConnectTestCALeafRootChangeSpread"`
		ConsulCoordinateUpdateBatchSize        int           `json:"ConsulCoordinateUpdateBatchSize"`
		ConsulCoordinateUpdateMaxBatches       int           `json:"ConsulCoordinateUpdateMaxBatches"`
		ConsulCoordinateUpdatePeriod           string        `json:"ConsulCoordinateUpdatePeriod"`
		ConsulRaftElectionTimeout              string        `json:"ConsulRaftElectionTimeout"`
		ConsulRaftHeartbeatTimeout             string        `json:"ConsulRaftHeartbeatTimeout"`
		ConsulRaftLeaderLeaseTimeout           string        `json:"ConsulRaftLeaderLeaseTimeout"`
		ConsulServerHealthInterval             string        `json:"ConsulServerHealthInterval"`
		DNSARecordLimit                        int           `json:"DNSARecordLimit"`
		DNSAddrs                               []string      `json:"DNSAddrs"`
		DNSAllowStale                          bool          `json:"DNSAllowStale"`
		DNSAltDomain                           string        `json:"DNSAltDomain"`
		DNSCacheMaxAge                         string        `json:"DNSCacheMaxAge"`
		DNSDisableCompression                  bool          `json:"DNSDisableCompression"`
		DNSDomain                              string        `json:"DNSDomain"`
		DNSEnableTruncate                      bool          `json:"DNSEnableTruncate"`
		DNSMaxStale                            string        `json:"DNSMaxStale"`
		DNSNodeMetaTXT                         bool          `json:"DNSNodeMetaTXT"`
		DNSNodeTTL                             string        `json:"DNSNodeTTL"`
		DNSOnlyPassing                         bool          `json:"DNSOnlyPassing"`
		DNSPort                                int           `json:"DNSPort"`
		DNSRecursorTimeout                     string        `json:"DNSRecursorTimeout"`
		DNSRecursors                           []interface{} `json:"DNSRecursors"`
		DNSSOA                                 struct {
			Expire  int `json:"Expire"`
			Minttl  int `json:"Minttl"`
			Refresh int `json:"Refresh"`
			Retry   int `json:"Retry"`
		} `json:"DNSSOA"`
		DNSServiceTTL struct {
		} `json:"DNSServiceTTL"`
		DNSUDPAnswerLimit                int    `json:"DNSUDPAnswerLimit"`
		DNSUseCache                      bool   `json:"DNSUseCache"`
		DataDir                          string `json:"DataDir"`
		Datacenter                       string `json:"Datacenter"`
		DefaultQueryTime                 string `json:"DefaultQueryTime"`
		DevMode                          bool   `json:"DevMode"`
		DisableAnonymousSignature        bool   `json:"DisableAnonymousSignature"`
		DisableCoordinates               bool   `json:"DisableCoordinates"`
		DisableHTTPUnprintableCharFilter bool   `json:"DisableHTTPUnprintableCharFilter"`
		DisableHostNodeID                bool   `json:"DisableHostNodeID"`
		DisableKeyringFile               bool   `json:"DisableKeyringFile"`
		DisableRemoteExec                bool   `json:"DisableRemoteExec"`
		DisableUpdateCheck               bool   `json:"DisableUpdateCheck"`
		DiscardCheckOutput               bool   `json:"DiscardCheckOutput"`
		DiscoveryMaxStale                string `json:"DiscoveryMaxStale"`
		EnableAgentTLSForChecks          bool   `json:"EnableAgentTLSForChecks"`
		EnableCentralServiceConfig       bool   `json:"EnableCentralServiceConfig"`
		EnableDebug                      bool   `json:"EnableDebug"`
		EnableLocalScriptChecks          bool   `json:"EnableLocalScriptChecks"`
		EnableRemoteScriptChecks         bool   `json:"EnableRemoteScriptChecks"`
		EncryptKey                       string `json:"EncryptKey"`
		EncryptVerifyIncoming            bool   `json:"EncryptVerifyIncoming"`
		EncryptVerifyOutgoing            bool   `json:"EncryptVerifyOutgoing"`
		EnterpriseRuntimeConfig          struct {
		} `json:"EnterpriseRuntimeConfig"`
		ExposeMaxPort           int           `json:"ExposeMaxPort"`
		ExposeMinPort           int           `json:"ExposeMinPort"`
		GRPCAddrs               []interface{} `json:"GRPCAddrs"`
		GRPCPort                int           `json:"GRPCPort"`
		GossipLANGossipInterval string        `json:"GossipLANGossipInterval"`
		GossipLANGossipNodes    int           `json:"GossipLANGossipNodes"`
		GossipLANProbeInterval  string        `json:"GossipLANProbeInterval"`
		GossipLANProbeTimeout   string        `json:"GossipLANProbeTimeout"`
		GossipLANRetransmitMult int           `json:"GossipLANRetransmitMult"`
		GossipLANSuspicionMult  int           `json:"GossipLANSuspicionMult"`
		GossipWANGossipInterval string        `json:"GossipWANGossipInterval"`
		GossipWANGossipNodes    int           `json:"GossipWANGossipNodes"`
		GossipWANProbeInterval  string        `json:"GossipWANProbeInterval"`
		GossipWANProbeTimeout   string        `json:"GossipWANProbeTimeout"`
		GossipWANRetransmitMult int           `json:"GossipWANRetransmitMult"`
		GossipWANSuspicionMult  int           `json:"GossipWANSuspicionMult"`
		HTTPAddrs               []string      `json:"HTTPAddrs"`
		HTTPBlockEndpoints      []interface{} `json:"HTTPBlockEndpoints"`
		HTTPMaxConnsPerClient   int           `json:"HTTPMaxConnsPerClient"`
		HTTPMaxHeaderBytes      int           `json:"HTTPMaxHeaderBytes"`
		HTTPPort                int           `json:"HTTPPort"`
		HTTPResponseHeaders     struct {
		} `json:"HTTPResponseHeaders"`
		HTTPSAddrs            []interface{} `json:"HTTPSAddrs"`
		HTTPSHandshakeTimeout string        `json:"HTTPSHandshakeTimeout"`
		HTTPSPort             int           `json:"HTTPSPort"`
		HTTPUseCache          bool          `json:"HTTPUseCache"`
		KVMaxValueSize        int           `json:"KVMaxValueSize"`
		KeyFile               string        `json:"KeyFile"`
		LeaveDrainTime        string        `json:"LeaveDrainTime"`
		LeaveOnTerm           bool          `json:"LeaveOnTerm"`
		Logging               struct {
			EnableSyslog      bool   `json:"EnableSyslog"`
			LogFilePath       string `json:"LogFilePath"`
			LogJSON           bool   `json:"LogJSON"`
			LogLevel          string `json:"LogLevel"`
			LogRotateBytes    int    `json:"LogRotateBytes"`
			LogRotateDuration string `json:"LogRotateDuration"`
			LogRotateMaxFiles int    `json:"LogRotateMaxFiles"`
			Name              string `json:"Name"`
			SyslogFacility    string `json:"SyslogFacility"`
		} `json:"Logging"`
		MaxQueryTime string `json:"MaxQueryTime"`
		NodeID       string `json:"NodeID"`
		NodeMeta     struct {
		} `json:"NodeMeta"`
		NodeName                string        `json:"NodeName"`
		PidFile                 string        `json:"PidFile"`
		PrimaryDatacenter       string        `json:"PrimaryDatacenter"`
		PrimaryGateways         []interface{} `json:"PrimaryGateways"`
		PrimaryGatewaysInterval string        `json:"PrimaryGatewaysInterval"`
		RPCAdvertiseAddr        string        `json:"RPCAdvertiseAddr"`
		RPCBindAddr             string        `json:"RPCBindAddr"`
		RPCConfig               struct {
			EnableStreaming bool `json:"EnableStreaming"`
		} `json:"RPCConfig"`
		RPCHandshakeTimeout         string        `json:"RPCHandshakeTimeout"`
		RPCHoldTimeout              string        `json:"RPCHoldTimeout"`
		RPCMaxBurst                 int           `json:"RPCMaxBurst"`
		RPCMaxConnsPerClient        int           `json:"RPCMaxConnsPerClient"`
		RPCProtocol                 int           `json:"RPCProtocol"`
		RPCRateLimit                int           `json:"RPCRateLimit"`
		RaftProtocol                int           `json:"RaftProtocol"`
		RaftSnapshotInterval        string        `json:"RaftSnapshotInterval"`
		RaftSnapshotThreshold       int           `json:"RaftSnapshotThreshold"`
		RaftTrailingLogs            int           `json:"RaftTrailingLogs"`
		ReadReplica                 bool          `json:"ReadReplica"`
		ReconnectTimeoutLAN         string        `json:"ReconnectTimeoutLAN"`
		ReconnectTimeoutWAN         string        `json:"ReconnectTimeoutWAN"`
		RejoinAfterLeave            bool          `json:"RejoinAfterLeave"`
		RetryJoinIntervalLAN        string        `json:"RetryJoinIntervalLAN"`
		RetryJoinIntervalWAN        string        `json:"RetryJoinIntervalWAN"`
		RetryJoinLAN                []string      `json:"RetryJoinLAN"`
		RetryJoinMaxAttemptsLAN     int           `json:"RetryJoinMaxAttemptsLAN"`
		RetryJoinMaxAttemptsWAN     int           `json:"RetryJoinMaxAttemptsWAN"`
		RetryJoinWAN                []interface{} `json:"RetryJoinWAN"`
		Revision                    string        `json:"Revision"`
		SegmentLimit                int           `json:"SegmentLimit"`
		SegmentName                 string        `json:"SegmentName"`
		SegmentNameLimit            int           `json:"SegmentNameLimit"`
		Segments                    []interface{} `json:"Segments"`
		SerfAdvertiseAddrLAN        string        `json:"SerfAdvertiseAddrLAN"`
		SerfAdvertiseAddrWAN        string        `json:"SerfAdvertiseAddrWAN"`
		SerfAllowedCIDRsLAN         []interface{} `json:"SerfAllowedCIDRsLAN"`
		SerfAllowedCIDRsWAN         []interface{} `json:"SerfAllowedCIDRsWAN"`
		SerfBindAddrLAN             string        `json:"SerfBindAddrLAN"`
		SerfBindAddrWAN             string        `json:"SerfBindAddrWAN"`
		SerfPortLAN                 int           `json:"SerfPortLAN"`
		SerfPortWAN                 int           `json:"SerfPortWAN"`
		ServerMode                  bool          `json:"ServerMode"`
		ServerName                  string        `json:"ServerName"`
		ServerPort                  int           `json:"ServerPort"`
		Services                    []interface{} `json:"Services"`
		SessionTTLMin               string        `json:"SessionTTLMin"`
		SkipLeaveOnInt              bool          `json:"SkipLeaveOnInt"`
		StartJoinAddrsLAN           []interface{} `json:"StartJoinAddrsLAN"`
		StartJoinAddrsWAN           []interface{} `json:"StartJoinAddrsWAN"`
		SyncCoordinateIntervalMin   string        `json:"SyncCoordinateIntervalMin"`
		SyncCoordinateRateTarget    int           `json:"SyncCoordinateRateTarget"`
		TLSCipherSuites             []interface{} `json:"TLSCipherSuites"`
		TLSMinVersion               string        `json:"TLSMinVersion"`
		TLSPreferServerCipherSuites bool          `json:"TLSPreferServerCipherSuites"`
		TaggedAddresses             struct {
			Lan     string `json:"lan"`
			LanIpv4 string `json:"lan_ipv4"`
			Wan     string `json:"wan"`
			WanIpv4 string `json:"wan_ipv4"`
		} `json:"TaggedAddresses"`
		Telemetry struct {
			AllowedPrefixes                    []interface{} `json:"AllowedPrefixes"`
			BlockedPrefixes                    []interface{} `json:"BlockedPrefixes"`
			CirconusAPIApp                     string        `json:"CirconusAPIApp"`
			CirconusAPIToken                   string        `json:"CirconusAPIToken"`
			CirconusAPIURL                     string        `json:"CirconusAPIURL"`
			CirconusBrokerID                   string        `json:"CirconusBrokerID"`
			CirconusBrokerSelectTag            string        `json:"CirconusBrokerSelectTag"`
			CirconusCheckDisplayName           string        `json:"CirconusCheckDisplayName"`
			CirconusCheckForceMetricActivation string        `json:"CirconusCheckForceMetricActivation"`
			CirconusCheckID                    string        `json:"CirconusCheckID"`
			CirconusCheckInstanceID            string        `json:"CirconusCheckInstanceID"`
			CirconusCheckSearchTag             string        `json:"CirconusCheckSearchTag"`
			CirconusCheckTags                  string        `json:"CirconusCheckTags"`
			CirconusSubmissionInterval         string        `json:"CirconusSubmissionInterval"`
			CirconusSubmissionURL              string        `json:"CirconusSubmissionURL"`
			Disable                            bool          `json:"Disable"`
			DisableCompatOneNine               bool          `json:"DisableCompatOneNine"`
			DisableHostname                    bool          `json:"DisableHostname"`
			DogstatsdAddr                      string        `json:"DogstatsdAddr"`
			DogstatsdTags                      []interface{} `json:"DogstatsdTags"`
			FilterDefault                      bool          `json:"FilterDefault"`
			MetricsPrefix                      string        `json:"MetricsPrefix"`
			PrometheusOpts                     struct {
				CounterDefinitions []interface{} `json:"CounterDefinitions"`
				Expiration         string        `json:"Expiration"`
				GaugeDefinitions   []interface{} `json:"GaugeDefinitions"`
				Registerer         interface{}   `json:"Registerer"`
				SummaryDefinitions []interface{} `json:"SummaryDefinitions"`
			} `json:"PrometheusOpts"`
			StatsdAddr   string `json:"StatsdAddr"`
			StatsiteAddr string `json:"StatsiteAddr"`
		} `json:"Telemetry"`
		TranslateWANAddrs bool `json:"TranslateWANAddrs"`
		TxnMaxReqLen      int  `json:"TxnMaxReqLen"`
		UIConfig          struct {
			ContentPath           string `json:"ContentPath"`
			DashboardURLTemplates struct {
			} `json:"DashboardURLTemplates"`
			Dir                        string        `json:"Dir"`
			Enabled                    bool          `json:"Enabled"`
			MetricsProvider            string        `json:"MetricsProvider"`
			MetricsProviderFiles       []interface{} `json:"MetricsProviderFiles"`
			MetricsProviderOptionsJSON string        `json:"MetricsProviderOptionsJSON"`
			MetricsProxy               struct {
				AddHeaders    []interface{} `json:"AddHeaders"`
				BaseURL       string        `json:"BaseURL"`
				PathAllowlist []interface{} `json:"PathAllowlist"`
			} `json:"MetricsProxy"`
		} `json:"UIConfig"`
		UnixSocketGroup      string        `json:"UnixSocketGroup"`
		UnixSocketMode       string        `json:"UnixSocketMode"`
		UnixSocketUser       string        `json:"UnixSocketUser"`
		UseStreamingBackend  bool          `json:"UseStreamingBackend"`
		VerifyIncoming       bool          `json:"VerifyIncoming"`
		VerifyIncomingHTTPS  bool          `json:"VerifyIncomingHTTPS"`
		VerifyIncomingRPC    bool          `json:"VerifyIncomingRPC"`
		VerifyOutgoing       bool          `json:"VerifyOutgoing"`
		VerifyServerHostname bool          `json:"VerifyServerHostname"`
		Version              string        `json:"Version"`
		VersionPrerelease    string        `json:"VersionPrerelease"`
		Watches              []interface{} `json:"Watches"`
	} `json:"DebugConfig"`
	Coord struct {
		Vec        []float64 `json:"Vec"`
		Error      float64   `json:"Error"`
		Adjustment float64   `json:"Adjustment"`
		Height     float64   `json:"Height"`
	} `json:"Coord"`
	Member struct {
		Name string `json:"Name"`
		Addr string `json:"Addr"`
		Port int    `json:"Port"`
		Tags struct {
			Acls        string `json:"acls"`
			Build       string `json:"build"`
			Dc          string `json:"dc"`
			Expect      string `json:"expect"`
			FtFs        string `json:"ft_fs"`
			FtSi        string `json:"ft_si"`
			Id          string `json:"id"`
			Port        string `json:"port"`
			RaftVsn     string `json:"raft_vsn"`
			Role        string `json:"role"`
			Segment     string `json:"segment"`
			UseTls      string `json:"use_tls"`
			Vsn         string `json:"vsn"`
			VsnMax      string `json:"vsn_max"`
			VsnMin      string `json:"vsn_min"`
			WanJoinPort string `json:"wan_join_port"`
		} `json:"Tags"`
		Status      int `json:"Status"`
		ProtocolMin int `json:"ProtocolMin"`
		ProtocolMax int `json:"ProtocolMax"`
		ProtocolCur int `json:"ProtocolCur"`
		DelegateMin int `json:"DelegateMin"`
		DelegateMax int `json:"DelegateMax"`
		DelegateCur int `json:"DelegateCur"`
	} `json:"Member"`
	Stats struct {
		Agent struct {
			CheckMonitors string `json:"check_monitors"`
			CheckTtls     string `json:"check_ttls"`
			Checks        string `json:"checks"`
			Services      string `json:"services"`
		} `json:"agent"`
		Build struct {
			Prerelease string `json:"prerelease"`
			Revision   string `json:"revision"`
			Version    string `json:"version"`
		} `json:"build"`
		Consul struct {
			Acl              string `json:"acl"`
			Bootstrap        string `json:"bootstrap"`
			KnownDatacenters string `json:"known_datacenters"`
			Leader           string `json:"leader"`
			LeaderAddr       string `json:"leader_addr"`
			Server           string `json:"server"`
		} `json:"consul"`
		Raft struct {
			AppliedIndex             string `json:"applied_index"`
			CommitIndex              string `json:"commit_index"`
			FsmPending               string `json:"fsm_pending"`
			LastContact              string `json:"last_contact"`
			LastLogIndex             string `json:"last_log_index"`
			LastLogTerm              string `json:"last_log_term"`
			LastSnapshotIndex        string `json:"last_snapshot_index"`
			LastSnapshotTerm         string `json:"last_snapshot_term"`
			LatestConfiguration      string `json:"latest_configuration"`
			LatestConfigurationIndex string `json:"latest_configuration_index"`
			NumPeers                 string `json:"num_peers"`
			ProtocolVersion          string `json:"protocol_version"`
			ProtocolVersionMax       string `json:"protocol_version_max"`
			ProtocolVersionMin       string `json:"protocol_version_min"`
			SnapshotVersionMax       string `json:"snapshot_version_max"`
			SnapshotVersionMin       string `json:"snapshot_version_min"`
			State                    string `json:"state"`
			Term                     string `json:"term"`
		} `json:"raft"`
		Runtime struct {
			Arch       string `json:"arch"`
			CpuCount   string `json:"cpu_count"`
			Goroutines string `json:"goroutines"`
			MaxProcs   string `json:"max_procs"`
			Os         string `json:"os"`
			Version    string `json:"version"`
		} `json:"runtime"`
		SerfLan struct {
			CoordinateResets string `json:"coordinate_resets"`
			Encrypted        string `json:"encrypted"`
			EventQueue       string `json:"event_queue"`
			EventTime        string `json:"event_time"`
			Failed           string `json:"failed"`
			HealthScore      string `json:"health_score"`
			IntentQueue      string `json:"intent_queue"`
			Left             string `json:"left"`
			MemberTime       string `json:"member_time"`
			Members          string `json:"members"`
			QueryQueue       string `json:"query_queue"`
			QueryTime        string `json:"query_time"`
		} `json:"serf_lan"`
		SerfWan struct {
			CoordinateResets string `json:"coordinate_resets"`
			Encrypted        string `json:"encrypted"`
			EventQueue       string `json:"event_queue"`
			EventTime        string `json:"event_time"`
			Failed           string `json:"failed"`
			HealthScore      string `json:"health_score"`
			IntentQueue      string `json:"intent_queue"`
			Left             string `json:"left"`
			MemberTime       string `json:"member_time"`
			Members          string `json:"members"`
			QueryQueue       string `json:"query_queue"`
			QueryTime        string `json:"query_time"`
		} `json:"serf_wan"`
	} `json:"Stats"`
	Meta struct {
		ConsulNetworkSegment string `json:"consul-network-segment"`
	} `json:"Meta"`
}
